Repository EMCECS/charts, pull requests merged in 2020-12, with the labels that each got.

#542 [MONITORINTG-1021] Install logging injector with install controller
  Makefile
  logging-injector/Chart.yaml
  logging-injector/README.md
  logging-injector/charts/logging-injector-3.7.0-1086.35c6c892.tgz
  logging-injector/templates/logging-injector-app.yaml
  logging-injector/values.yaml
  vmware/vmware_pack.sh
Labels: monitoring

#543 [OBSDEF-4332] Fix Operator RBAC for storagepools
  objectscale-manager/templates/operator-rbac.yaml
Labels: bug

#544 [MONITORING-1021] Update install controller tag
  helm-controller/values.yaml
  objectscale-graphql/charts/helm-controller-0.61.0.tgz
  objectscale-vsphere/charts/objectscale-graphql-0.61.0.tgz
Labels: monitoring

#545 [OBSDEF-4332] Fix Operator RBAC for storagepools
  objectscale-manager/templates/operator-rbac.yaml
Labels: bug

#541 [MONITORING-1004] Tools for Alert report auto-generation
  Makefile
  tools/issues_events_report/issues_events_reporter.py
Labels: monitoring, serviceability

#548 [OBSDEF-4080] Rename common-lib chart to common-monitoring-lib
  influxdb-operator/Chart.yaml
  influxdb-operator/charts/common-lib-3.7.0-1089.c03efdd9.tgz
  influxdb-operator/charts/common-monitoring-lib-3.7.0-1093.68e15221.tgz
  influxdb-operator/templates/deployment.yaml
  statefuldaemonset-operator/Chart.yaml
  statefuldaemonset-operator/charts/common-lib-3.7.0-1089.c03efdd9.tgz
  statefuldaemonset-operator/charts/common-monitoring-lib-3.7.0-1093.68e15221.tgz
  statefuldaemonset-operator/templates/deployment.yaml
Labels: monitoring

#549 Feature monitoring 1022 rsyslog client single role
  ecs-cluster/values.yaml
Labels: monitoring

#550 [OBSDEF-4080] Add logging sidecar to GraphQL chart
  objectscale-graphql/Chart.yaml
  objectscale-graphql/charts/common-monitoring-lib-3.7.0-1093.ae5ea5e2.tgz
  objectscale-graphql/templates/graphql-deployment.yaml
  objectscale-graphql/tests/graphql_deploy_test.yaml
  objectscale-vsphere/Chart.yaml
  objectscale-vsphere/charts/rsyslog-client-3.7.0-1093.ae5ea5e2.tgz
  objectscale-vsphere/values.yaml
Labels: monitoring
