Repository EMCECS/charts, pull requests merged in 2021-04, with the labels that each got.

#706 [OBSDEF-7081] Add fed svc name env variable in the operator
  objectscale-manager/templates/operator.yaml
Labels: enhancement, federation, operator

#717 [OBSDEF-7023] Update ZK version
  docs/index.yaml
  docs/zookeeper-operator-0.2.10.tgz
  docs/zookeeper-operator-0.2.9.tgz
  objectscale-manager/charts/zookeeper-operator-0.2.10.tgz
  objectscale-manager/charts/zookeeper-operator-0.2.9.tgz
  zookeeper-operator/Chart.yaml
  zookeeper-operator/values.yaml
Labels: bug

#723 [OBSDEF-7340] Labels for sp operator
  Makefile
  common-lib/.helmignore
  common-lib/Chart.yaml
  common-lib/templates/_sp_operator_labels.yaml
  common-lib/values.yaml
  influxdb-operator/Chart.yaml
  influxdb-operator/charts/common-lib-0.71.2.tgz
  influxdb-operator/templates/deployment.yaml
  statefuldaemonset-operator/Chart.yaml
  statefuldaemonset-operator/charts/common-lib-0.71.2.tgz
  statefuldaemonset-operator/templates/deployment.yaml
Labels: enhancement

#725 [OBSDEF-7516] - add objectscale-api configmaps for new graphql informer code.
  atlas-operator/Chart.yaml
  bookkeeper-operator/Chart.yaml
  docs/index.yaml
  docs/objectscale-graphql-0.71.2.tgz
  docs/objectscale-portal-0.71.2.tgz
  docs/objectscale-vsphere-0.71.2.tgz
  objectscale-charts-package.tgz
  objectscale-graphql/charts/helm-controller-0.71.2.tgz
  objectscale-graphql/templates/objectscale-admin-cluster-role.yaml
  objectscale-portal/charts/objectscale-graphql-0.71.2.tgz
  objectscale-vsphere/charts/objectscale-portal-0.71.2.tgz
  pravega-operator/Chart.yaml
  temp_package/scripts/deploy-objectscale-plugin.sh
  temp_package/yaml/decks.yaml
  temp_package/yaml/kahm.yaml
  temp_package/yaml/logging-injector.yaml
  temp_package/yaml/objectscale-crd.yaml
  temp_package/yaml/objectscale-manager.yaml
  zookeeper-operator/Chart.yaml
Labels: mustfix

#715 [OBSDEF-1914] Add SupportAssist field to test connectivity on demand
  Makefile
  supportassist/templates/supportassist-cr.yaml
Labels: enhancement
