Repository EMCECS/charts, pull requests merged in 2021-08, with the labels that each got.

#929 [OBSDEF] Fix chart missing values
  ecs-cluster/values.yaml
  logging-injector/templates/logging-injector-app-config.yaml
  logging-injector/values.yaml
Labels: bug

#930 [OBSDEF-10551] fix ecs template in respect of handling topology feature values
  ecs-cluster/templates/ecs-cluster.yaml
Labels: bug

#937 [OBSDEF-10551] node affinity rules for object store
  ecs-cluster/templates/_helpers.tpl
  ecs-cluster/templates/ecs-cluster.yaml
Labels: bug, enhancement

#941 [OBSDEF-10965] Added WATCH_NAMESPACE env variable to the federation pods.
  objectscale-federation/templates/federation_deployment.yaml
Labels: federation

#935 [OBSDEF-7255] ability to pass storageclass for atlas
  ecs-cluster/templates/ecs-cluster.yaml
  objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml
  objectscale-dcm/values.yaml
  objectscale-federation/templates/atlas_v1beta1_fedcluster.yaml
  objectscale-federation/values.yaml
  objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
  objectscale-iam/values.yaml
Labels: enhancement, atlas

#940 [OBSDEF-10704] Add node name and pvc name fields for ServiceProcedure CRD
  objectscale-manager/crds/dellemc.com_serviceprocedures_crd.yaml
Labels: enhancement, operator

#946 [OBSDEF-8116][OBSDEF-11079] - New code required for vs7u3 automation, retiring openshift scripts
  scripts/scripts_pkg.sh
Labels: vSphere7

#944 [OBSDEF-10984] Fix pre-update healthcheck RBAC
  logging-injector/templates/healthcheck-rbac.yaml
  supportassist/templates/healthcheck-rbac.yaml
Labels: bug

#939 [OBSDEF-8797] Update the permission group for support assist
  supportassist/templates/supportassist.yaml
Labels: bug

#952 [OBSDEF-11132] remove check for watch all ns for edit/view/admin clus…
  objectscale-graphql/templates/object-store-admin-role.yaml
  objectscale-graphql/templates/object-store-monitor-role.yaml
Labels: bug

#950 [OBSDEF-10725] Enable stdout logs collection on vsphere by default
  Makefile
Labels: monitoring

#958 [OBSDEF-10597] Refactor SP operator ignore checks labels
  common-lib/templates/_sp_operator_labels.yaml
  ecs-cluster/templates/ecs-cluster.yaml
  objectscale-iam/values.yaml
Labels: operator

#957 [OBSDEF-10940] Issues related to ObjectStore SP are not shown
  ecs-cluster/alerts/issues/OBJSOP-1000_DISK_REPLACEMENT_issue.yaml
  ecs-cluster/alerts/issues/OBJSOP-1001_PMM_issue.yaml
  ecs-cluster/alerts/issues/OBJSOP-1002_TMM_issue.yaml
  ecs-cluster/alerts/issues/OBJSOP-1003_UPGRADE_issue.yaml
  ecs-cluster/alerts/issues/OBJSOP-1004_HORIZONTAL_EXPAND_issue.yaml
  ecs-cluster/alerts/issues/OBJSOP-1004_VERTICAL_EXPAND_issue.yaml
  ecs-cluster/alerts/remedies/OBJSOP-1000_DISK_REPLACEMENT_remedies.yaml
  ecs-cluster/alerts/remedies/OBJSOP-1001_PMM_remedies.yaml
  ecs-cluster/alerts/remedies/OBJSOP-1002_TMM_remedies.yaml
  ecs-cluster/alerts/remedies/OBJSOP-1003_UPGRADE_remedies.yaml
  ecs-cluster/alerts/remedies/OBJSOP-1004_HORIZONTAL_EXPAND_remedies.yaml
  ecs-cluster/alerts/remedies/OBJSOP-1004_VERTICAL_EXPAND_remedies.yaml
Labels: bug, operator

#938 [OBSDEF-10894] add Alert for CRR - REPLICATION_EVENT_RETRY_LIMIT_EXCEEDED
  ecs-cluster/alerts/issues/12007_REPLICATION_EVENT_RETRY_LIMIT_EXCEEDED.yaml
Labels: mustfix

#962 [OBSDEF-11100] Updated liveness script for objectscale-gateway and objectscale-gateway-internal
  objectscale-gateway/templates/deployment.yaml
Labels: mustfix

#968 [OBSDEF-11100] Updated liveness script for objectscale-gateway and objectscale-gateway-internal
  objectscale-gateway/templates/deployment.yaml
Labels: mustfix

#966 [OBSDEF-10711] statefuldaemonset-operator: role updates for persistentvolumeclaims
  statefuldaemonset-operator/templates/role.yaml
Labels: mustfix
