Repository EMCECS/charts, pull requests merged in 2021-09, with the labels that each got.

#965 [OBSDEF-6122] change geoservice log level
  ecs-cluster/svc-configs/geoservice/geoservice-log4j2.xml
Labels: mustfix

#972 [OBSDEF-8292] There is no way by which TMM rejection by Operator can be bypassed. Bypass TMM checks
  objectscale-manager/templates/objectscale-manager-bypass-configmap.yaml
  objectscale-manager/templates/operator.yaml
Labels: operator

#987 [OBSDEF-11310] Pre-DR timeout
  objectscale-manager/templates/operator-nodefail-configmap.yaml
Labels: enhancement

#991 [OBSDEF-8163] By pass checks for PMM
  objectscale-manager/templates/objectscale-manager-bypass-configmap.yaml
Labels: operator

#995 [OBSDEF-11433] Change nodeSelector terms to excluded nodes list
  ecs-cluster/templates/_helpers.tpl
  ecs-cluster/templates/ecs-cluster.yaml
  ecs-cluster/values.yaml
Labels: bug

#996 [OBSDEF-4965] Add basic RBAC for service pod
  service-pod/templates/deployment.yaml
  service-pod/templates/rbac.yaml
Labels: bug, enhancement, serviceability

#1006 [OBSDEF-10613] Add custom args support in make vsphere
  Makefile
  objectscale-graphql/templates/graphql-deployment.yaml
Labels: enhancement

#1012 [OBSDEF-11543][OBSDEF-11544] add ons-conf and nds-conf configmaps
  ecs-cluster/templates/svc-configs.yaml
  ecs-cluster/tests/svc_log4j2_test.yaml
Labels: enhancement

#1024 [OBSDEF-12205] Service pod should have admin privileges
  service-pod/templates/deployment.yaml
  service-pod/templates/rbac.yaml
Labels: bug, mustfix
