Repository EMCECS/charts, pull requests merged in 2021-06, with the labels that each got.

#817 [OBSDEF-8967] Operator: add ability to list/get volumes.csi-baremetal.dell.com
  objectscale-manager/templates/operator-rbac.yaml
Labels: bug, operator

#816 [OBSDEF-8955] Add DECKS upgrade support & custom settings
  Makefile
  decks/decks-custom-values.yaml
  decks/templates/decks-app.yaml
Labels: enhancement

#808 [OBSDEF-3870] Make KAHM only set custom values
  Makefile
  kahm/kahm-custom-values.yaml
  kahm/templates/kahm-app.yaml
Labels: enhancement, help wanted

#815 [OBSDEF-7181] change dcm to static name similar to other objectscale services
  Makefile
  README.md
  dcm/charts/common-lib-0.74.0.tgz
  docs/objectscale-dcm-0.74.0.tgz
  objectscale-dcm/.helmignore
  objectscale-dcm/Chart.yaml
  objectscale-dcm/charts/common-lib-0.74.0.tgz
  objectscale-dcm/charts/common-monitoring-lib-3.7.0-1209.a2bfd98b.tgz
  objectscale-dcm/templates/_helpers.tpl
  objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml
  objectscale-dcm/templates/dcm-log-configmap.yaml
  objectscale-dcm/templates/deployment.yaml
  objectscale-dcm/templates/service.yaml
  objectscale-dcm/values.yaml
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/dcm-0.74.0.tgz
  objectscale-manager/charts/objectscale-dcm-0.74.0.tgz
  objectscale-manager/templates/operator.yaml
Labels: dcm

#824 OBSDEF-9025 - Update decks deployment to quote env variables
  decks-support-store/charts/common-lib-0.74.0.tgz
  decks/charts/common-lib-0.74.0.tgz
  decks/charts/decks-support-store-2.74.0.tgz
  decks/templates/decks.yaml
  docs/decks-2.74.0.tgz
  docs/decks-support-store-2.74.0.tgz
  docs/index.yaml
Labels: bug, mustfix, serviceability

#827 [OBSDEF-8958] revert dcm service type to loadBalancer
  objectscale-dcm/values.yaml
  objectscale-manager/charts/objectscale-dcm-0.74.0.tgz
Labels: dcm

#823 [OBSDEF-8704] telemetry report chart changes
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
  objectscale-manager/values.yaml
Labels: mustfix, serviceability

#830 [OBSDEF-8811] Create/Update KAHM events for licensing
  docs/index.yaml
  docs/objectscale-manager-0.74.0.tgz
  objectscale-charts-package.tgz
  objectscale-manager/alerts/issues/OBJSC-LIC-0004_licensing_issue.yaml
  objectscale-manager/alerts/remedies/OBJSC-LIC-0004_licensing_remedies.yaml
  objectscale-manager/charts/atlas-operator-0.31.0.tgz
  objectscale-manager/charts/bookkeeper-operator-0.1.3.tgz
  objectscale-manager/charts/common-lib-0.74.0.tgz
  objectscale-manager/charts/federation-0.74.0.tgz
  objectscale-manager/charts/objectscale-dcm-0.74.0.tgz
  objectscale-manager/charts/objectscale-gateway-0.74.0.tgz
  objectscale-manager/charts/objectscale-iam-0.74.0.tgz
  objectscale-manager/charts/pravega-operator-0.5.2.tgz
  objectscale-manager/charts/service-pod-2.74.0.tgz
  objectscale-manager/charts/zookeeper-operator-0.2.10.tgz
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
  objectscale-manager/templates/telemetry-rbac.yaml
Labels: mustfix, serviceability

#828 [OBSDEF-9022] Add DECKS Preupdate Healthcheck
  .gitignore
  decks/templates/decks-app-configmap.yaml
  decks/templates/healthchecks-rbac.yaml
  decks/values.yaml
Labels: enhancement, mustfix, serviceability

#829 [OBSDEF-9031] Add KAHM preupdate healthcheck
  kahm/templates/healthchecks-rbac.yaml
  kahm/templates/kahm-app-configmap.yaml
  kahm/values.yaml
Labels: enhancement, mustfix, serviceability

#833 Enable SP operator by default
  objectscale-manager/values.yaml
Labels: enhancement, operator

#836 [OBSDEF-8172] Add fabric proxy rbac for enduser namespaces
  ecs-cluster/templates/fabric-proxy-api-token.yaml
  ecs-cluster/templates/fabric-proxy-rbac.yaml
Labels: enhancement, mustfix, operator

#843 [OBSDEF-9149] update atlas operator version
  atlas-operator/Chart.yaml
  atlas-operator/values.yaml
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/atlas-operator-0.31.0.tgz
  objectscale-manager/charts/atlas-operator-0.32.0.tgz
Labels: atlas

#840 [OBSDEF-9009] Integrate Operator with Baremetal CSI for DR
  objectscale-manager/templates/operator-rbac.yaml
Labels: enhancement

#846 [OBSDEF-9175] dcm encryption key
  objectscale-dcm/templates/deployment.yaml
  objectscale-dcm/templates/encryption-key.yaml
Labels: dcm

#848 [OBSDEF-8599] atlas and atlas-operator component lables
  atlas-operator/templates/_helpers.tpl
  atlas-operator/templates/deployment.yaml
  ecs-cluster/templates/ecs-cluster.yaml
  federation/templates/atlas_v1beta1_fedcluster.yaml
  objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml
  objectscale-iam/templates/atlas_v1beta1_iamcluster.yaml
Labels: atlas

#853 [OBSDEF-8958] change dcm service type to clusterIP
  objectscale-dcm/values.yaml
  objectscale-manager/charts/objectscale-dcm-0.75.0.tgz
Labels: dcm

#849 [OBSDEF-9302] set fixed dcm atlas replicas and disk resources for raft wal rotation
  objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml
  objectscale-dcm/values.yaml
Labels: atlas, dcm

#859 [OBSDEF-9389] [OBSDEF-8755] memory requests and limits for atlas and dcm
  atlas-operator/values.yaml
  objectscale-dcm/templates/atlas_v1beta1_dcmcluster.yaml
  objectscale-dcm/templates/deployment.yaml
  objectscale-dcm/values.yaml
Labels: atlas, dcm

#861 Bugfix obsdef 8783 add missing sp operator labels
  kahm/values.yaml
Labels: bug, operator

#854 [OBSDEF-9295] add bypass Config Map for SP operator
  objectscale-manager/templates/objectscale-manager-service-procedures-configmap.yaml
  objectscale-manager/templates/operator.yaml
Labels: enhancement, operator

#858 [OBSDEF-9143] Make logging injector upgradeable
  .gitignore
  Makefile
  logging-injector/logging-injector-custom-values.yaml
  logging-injector/templates/logging-injector-app.yaml
  logging-injector/values.yaml
Labels: enhancement
