Repository EMCECS/charts, pull requests merged in 2021-02, with the labels that each got.

#591 [OBSDEF-5283] expose dcm service hostname to ecs-cluster services
  objectscale-manager/templates/operator.yaml
Labels: dcm

#585 [OBSDEF-5284] configurable Atlas pods for dcm && dcm probes
  dcm/templates/atlas_v1beta1_dcmcluster.yaml
  dcm/templates/deployment.yaml
  dcm/values.yaml
  docs/dcm-0.65.0.tgz
  docs/index.yaml
  docs/objectscale-manager-0.65.0.tgz
Labels: dcm

#605 [OBSDEF-5606] update README with name changes for drop66
  objectscale-iam/README.md
Labels: iam

#620 OBSDEF-5766 - ObjectScale 0.64.3 beta1 build for docker registry deployments on vSphere7
  Makefile
  docs/ecs-cluster-0.64.3.tgz
  docs/helm-controller-0.64.3.tgz
  docs/index.yaml
  docs/objectscale-graphql-0.64.3.tgz
  docs/objectscale-manager-0.64.3.tgz
  docs/objectscale-vsphere-0.64.3.tgz
  ecs-cluster/Chart.yaml
  helm-controller/Chart.yaml
  helm-controller/values.yaml
  objectscale-graphql/Chart.yaml
  objectscale-graphql/charts/helm-controller-0.64.2.tgz
  objectscale-graphql/charts/helm-controller-0.64.3.tgz
  objectscale-graphql/values.yaml
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/atlas-operator-0.28.0.tgz
  objectscale-manager/charts/bookkeeper-operator-0.1.2.tgz
  objectscale-manager/charts/federation-0.64.0.tgz
  objectscale-manager/charts/iam-0.64.0.tgz
  objectscale-manager/charts/pravega-operator-0.5.1.tgz
  objectscale-manager/charts/service-pod-2.0.64.tgz
  objectscale-manager/charts/zookeeper-operator-0.2.9.tgz
  objectscale-vsphere/Chart.yaml
  objectscale-vsphere/charts/objectscale-graphql-0.64.2.tgz
  objectscale-vsphere/charts/objectscale-graphql-0.64.3.tgz
  objectscale-vsphere/values.yaml
Labels: mustfix

#623 [OBSDEF-5826] Update atlas-operator
  atlas-operator/Chart.yaml
  atlas-operator/crds/atlasclusters.yaml
  atlas-operator/templates/role.yaml
  atlas-operator/values.yaml
  docs/atlas-operator-0.29.0.tgz
  docs/index.yaml
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/atlas-operator-0.28.0.tgz
  objectscale-manager/charts/atlas-operator-0.29.0.tgz
Labels: enhancement

#626 [OBSDEF-5915] change service type and remove redundant tag
  dcm/templates/deployment.yaml
  dcm/templates/service.yaml
  dcm/values.yaml
  docs/dcm-0.67.0.tgz
  docs/index.yaml
  docs/objectscale-manager-0.67.0.tgz
Labels: dcm

#628 OBSDEF-5726 - Change dellemc-license managed-by in app resource so that managed by correct service
  dellemc-license/templates/dellemc-license-app-configmap.yaml
  dellemc-license/templates/dellemc-license-app.yaml
Labels: serviceability

#611 [OBSDEF-2002] Add support for dark site installations
  Makefile
  ecs-cluster/templates/ecs-cluster.yaml
  objectscale-portal-0.66.0.tgz
  objectscale-portal/templates/objectscale-portal-deployment.yaml
  objectscale-vsphere/templates/persistent-services-platform-sp-ha.yaml
  objectscale-vsphere/templates/vsphere-plugin-secrets.yaml
  vmware/vmware_pack.sh
Labels: enhancement, mustfix
