Repository EMCECS/charts, pull requests merged in 2021-01, with the labels that each got.

#554 [OBSDEF-4831] Fix healthcheck RBAC
  ecs-cluster/templates/healthcheck-rbac.yaml
  ecs-cluster/templates/objectstore-app-configmap.yaml
Labels: bug, enhancement

#566 [OBSDEF-4989] ConfigMaps for repsvc
  ecs-cluster/svc-configs/rep/repsvc-log4j2.xml
  ecs-cluster/templates/svc-configs.yaml
  ecs-cluster/tests/svc_log4j2_test.yaml
  ecs-cluster/values.yaml
Labels: enhancement

#565 [OBSDEF-3775] Add DCM charts
  Makefile
  dcm/.helmignore
  dcm/Chart.yaml
  dcm/templates/_helpers.tpl
  dcm/templates/atlas_v1beta1_dcmcluster.yaml
  dcm/templates/deployment.yaml
  dcm/templates/service.yaml
  dcm/values.yaml
  docs/dcm-0.64.0.tgz
  docs/index.yaml
  docs/objectscale-manager-0.64.0.tgz
  docs/objectscale-manager-0.64.2.tgz
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/dcm-0.64.0.tgz
  objectscale-manager/values.yaml
Labels: dcm

#577 [OBSDEF-5286] Delete wrong ecs-monitoring helm chart
  ecs-cluster/charts/ecs-monitoring-3.7.0+1079.45b85231.tgz
Labels: bug

#586 [MONITORING-1064][MONITORING-1065] Fixed permissions for rsyslog and influxdb operators
  influxdb-operator/templates/role.yaml
  statefuldaemonset-operator/templates/role.yaml
Labels: monitoring
