Repository EMCECS/charts, pull requests merged in 2021-03, with the labels that each got.

#643 [OBSDEF-5917] Use dedicated service account for atlas-operator
  atlas-operator/Chart.yaml
  atlas-operator/templates/deployment.yaml
  atlas-operator/templates/role.yaml
  atlas-operator/templates/role_binding.yaml
  atlas-operator/templates/serviceaccount.yaml
  atlas-operator/tests/role_binding_test.yaml
  atlas-operator/tests/serviceaccount_test.yaml
  docs/atlas-operator-0.31.0.tgz
  docs/index.yaml
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/atlas-operator-0.30.0.tgz
  objectscale-manager/charts/atlas-operator-0.31.0.tgz
Labels: enhancement

#654 [OBSDEF-6241] Remove schedule for pre-update check
  ecs-cluster/templates/objectstore-app-configmap.yaml
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
Labels: blocker, bug

#660 ATL-1561 - decks kahm 1.2.6 charts changes
  decks/Chart.yaml
  decks/values.yaml
  dellemc-license/Chart.yaml
  dellemc-license/values.yaml
  dks-testapp/Chart.yaml
  dks-testapp/values.yaml
  docs/decks-1.2.6.tgz
  docs/dellemc-license-1.2.6.tgz
  docs/dks-testapp-1.2.6.tgz
  docs/index.yaml
  docs/kahm-1.2.6.tgz
  docs/service-pod-1.2.6.tgz
  docs/srs-gateway-1.2.6.tgz
  kahm/Chart.yaml
  kahm/values.yaml
  service-pod/Chart.yaml
  service-pod/values.yaml
  srs-gateway/Chart.yaml
  srs-gateway/values.yaml
Labels: mustfix, serviceability

#670 [OBSDEF-6350] Add default args for pre-upgrades
  ecs-cluster/templates/objectstore-app-configmap.yaml
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
  objectscale-manager/values.yaml
Labels: bug, mustfix

#679 OBSDEF-6337 - 69.1 Re-enable pravega/bookkeeper and fire up bookie's as needed
  docs/ecs-cluster-0.69.1.tgz
  docs/helm-controller-0.69.1.tgz
  docs/index.yaml
  docs/objectscale-graphql-0.69.1.tgz
  docs/objectscale-manager-0.68.2.tgz
  docs/objectscale-manager-0.69.1.tgz
  docs/objectscale-portal-0.69.1.tgz
  docs/objectscale-vsphere-0.69.1.tgz
  ecs-cluster/Chart.yaml
  ecs-cluster/values.yaml
  helm-controller/Chart.yaml
  helm-controller/values.yaml
  objectscale-graphql/Chart.yaml
  objectscale-graphql/charts/helm-controller-0.69.0.tgz
  objectscale-graphql/charts/helm-controller-0.69.1.tgz
  objectscale-graphql/values.yaml
  objectscale-manager/Chart.yaml
  objectscale-manager/charts/atlas-operator-0.31.0.tgz
  objectscale-manager/charts/bookkeeper-operator-0.1.3.tgz
  objectscale-manager/charts/dcm-0.69.0.tgz
  objectscale-manager/charts/federation-0.69.0.tgz
  objectscale-manager/charts/objectscale-iam-0.69.0.tgz
  objectscale-manager/charts/pravega-operator-0.5.2.tgz
  objectscale-manager/charts/service-pod-2.69.0.tgz
  objectscale-manager/charts/zookeeper-operator-0.2.9.tgz
  objectscale-manager/values.yaml
  objectscale-portal/Chart.yaml
  objectscale-portal/charts/objectscale-graphql-0.69.0.tgz
  objectscale-portal/charts/objectscale-graphql-0.69.1.tgz
  objectscale-portal/values.yaml
  objectscale-vsphere/Chart.yaml
  objectscale-vsphere/charts/objectscale-portal-0.69.0.tgz
  objectscale-vsphere/charts/objectscale-portal-0.69.1.tgz
  temp_package/yaml/issues_events_0.69.0.json
  temp_package/yaml/issues_events_0.69.0.yaml
Labels: blocker, mustfix

#681 [OBSDEF-6531] support object store name `default`
  Makefile
  docs/ecs-cluster-0.69.1.tgz
  docs/index.yaml
  ecs-cluster/templates/ecs-cluster.yaml
  ecs-cluster/templates/objectstore-rbac.yaml
  ecs-cluster/tests/objectstore_rbac_test.yaml
Labels: bug

#684 [OBSDEF-6651] [OBSDEF-6775] [OBSDEF-193] - Charts update for build 70
  Makefile
  objectscale-manager/Chart.yaml
  objectscale-manager/values.yaml
Labels: mustfix

#689 [OBSDEF-6662] add missing dcm labels
  dcm/templates/_helpers.tpl
Labels: dcm
