Repository EMCECS/charts, pull requests merged in 2021-07, with the labels that each got.

#876 [OBSDEF-1996] Add configmap for skyline health
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
  objectscale-manager/values.yaml
  objectscale-vsphere/templates/skyline-health-configmap.yaml
Labels: enhancement

#880 [OBSDEF-9595] Allow Operator read StorageClass resources
  objectscale-manager/templates/operator-rbac.yaml
Labels: enhancement

#890 [OBSDEF-9800] Fix the typo for skyline health chart
  objectscale-vsphere/templates/skyline-health-configmap.yaml
Labels: enhancement

#892 [OBSDEF-9915]- build and pull in latest install-controller
  Dockerfile
  docs/index.yaml
  helm-controller/values.yaml
Labels: mustfix, vSphere7

#891 [OBSDEF-1996] Fix the cluster role for skyline health
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
  objectscale-manager/templates/telemetry-rbac.yaml
  objectscale-manager/values.yaml
Labels: enhancement

#874 [OBSDEF-7152] Add symptomID and remedy for preupdate checks
  decks/alerts/issues/DECKS-HC-1000_PRE_UPDATE_issue.yaml
  decks/alerts/remedies/DECKS-HC-1000_PRE_UPDATE_remedies.yaml
  decks/templates/decks-app-configmap.yaml
  ecs-cluster/alerts/issues/OBJSTORE-HC-1000_PRE_UPDATE_issue.yaml
  ecs-cluster/alerts/remedies/OBJSTORE-HC-1000_PRE_UPDATE_remedies.yaml
  ecs-cluster/templates/objectstore-app-configmap.yaml
  kahm/alerts/issues/KAHM-HC-1000_PRE_UPDATE_issue.yaml
  kahm/alerts/remedies/KAHM-HC-1000_PRE_UPDATE_remedies.yaml
  kahm/templates/kahm-app-configmap.yaml
  objectscale-manager/alerts/issues/OBJSC-MGR-HC-1000_PRE_UPDATE_issue.yaml
  objectscale-manager/alerts/remedies/OBJSC-MGR-HC-1000_PRE_UPDATE_remedies.yaml
  objectscale-manager/templates/objectscale-manager-app-configmap.yaml
Labels: enhancement

#900 [OBSDEF-9941] Add status field for ServiceProcedure CRD
  objectscale-manager/crds/dellemc.com_serviceprocedures_crd.yaml
Labels: enhancement, operator

#903 [OBSDEF-10025] Fix the cluster role for graphql
  objectscale-graphql/templates/objectscale-admin-cluster-role.yaml
Labels: bug

#912 [OBSDEF-10040] Fix fabric proxy rbac for baremetal
  ecs-cluster/templates/fabric-proxy-rbac.yaml
Labels: bug

#918 [OBSDEF-9632] fix missed changes for fedsvc rename
  objectscale-gateway/templates/configmap.yaml
  objectscale-portal/values.yaml
Labels: bug, federation

#902 [OBSDEF-9636] Add right resource labels
  decks/templates/decks.yaml
  kahm/templates/kahm.yaml
  supportassist/templates/supportassist.yaml
Labels: bug, enhancement

#917 [OBSDEF-10328] Add network policy if does not exist
  ecs-cluster/templates/networkpolicy.yaml
Labels: bug, enhancement

#927 [OBSDEF-10539] Add generic PUHC
  decks/values.yaml
  kahm/values.yaml
  logging-injector/templates/logging-injector-app-config.yaml
  logging-injector/values.yaml
  supportassist/templates/supportassist-app-configmap.yaml
  supportassist/values.yaml
Labels: enhancement
